[workspace]
members = ["ansi", "lines", "window"]

[package]
name = "wvim"
version = "0.1.0"
edition = "2024"

[dependencies]
lines = { path = "./lines/" }
ansi = { path = "./ansi/" }
window = { path = "./window/" }
termsize = "0.1.9"
